@startuml
'https://plantuml.com/class-diagram

class PlayerData{
    - PlayerDataListener listener;
        - int thoiGian, soLuotChoi, diemSo
        + void dangKy(PlayerDataListener listener)
        + void huyDangKy(PlayerDataListener listener)
        + void setThoiGian(int thoiGian)
        + void setDiemSo(int diemSo)
        + void setSoLuotChoi(int soLuotChoi)
}
class Dashboard
interface PlayerDataListener{
     + void listen(PlayerData p)
}
PlayerDataListener<|... Dashboard
PlayerData<--- PlayerDataListener:listen
Dashboard ---> PlayerData: playerData

@enduml