@startuml
'https://plantuml.com/class-diagram

abstract class Bnode{
    int value;
    +abstract void addL(Bnode n);
    +abstract void addR(Bnode n);
    +abstract void removeL(Bnode n);
    +abstract void removeR(Bnode n);
    +abstract String duyet();
}
Bnode<|--InnerBode
Bnode<|--Leaft
Bnode<--InnerBode:left
Bnode<--InnerBode:right
note right of Bnode::duyet
Phương thức duyệt in các giá trị trong cây theo thứ tự NRL
end note
@enduml